confrontos = "https://docs.google.com/spreadsheets/d/1fOtAkITJycuBoGWlYhQrYSjheYZTpoEwwtLBLKP7fC0/edit?gid=0#gid=0"
resultados = "https://docs.google.com/spreadsheets/d/12aIO3QHy1z8l8oM-5IInJdwRITdho1skNny4_a-UL9U/edit?gid=0#gid=0" 
